### ISSUE TITLE
Не работает ни на сервере, ни в локальной игре

### ISSUE THREAD

**Issue by MoccoCoffee** [kosmik641/gm_turbostroi#1]
Локальная игра:
![Screenshot from 2023-02-05 00-06-18](https://user-images.githubusercontent.com/52582484/216789765-f415e1a4-f0ac-4689-a7dd-e66cc71bf09a.png)

Консоль сервера:
![obraz](https://user-images.githubusercontent.com/52582484/216789789-9ae0de6f-99ac-42bc-9a39-993860b1565b.png)

**Comment by kosmik641** [comment]
Обсудили в личных сообщениях. Проблема скорее всего на стороне хостинга (ru-hoster)
